# See https://docs.gradle.org/current/userguide/compatibility.html
name: Java Compatibility Tests
on: [workflow_dispatch]
jobs:
  java8-12:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["5.1", "7.5.1"]
        java: ["8", "9", "10", "11", "12"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java13:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["6.0", "7.5.1"]
        java: ["13"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java14:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["6.3", "7.5.1"]
        java: ["14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java15:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["6.7", "7.5.1"]
        java: ["15"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java16:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.0", "7.5.1"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["16"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java17:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.3", "7.5.1"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["17"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java18:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.5", "7.5.1"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
  java-ea:
    name: "Compatibility: java ${{ matrix.java }}/gradle ${{ matrix.gradle }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        avro: ["1.11.0"]
        gradle: ["7.5.1"] # See here for latest versions: https://services.gradle.org/versions/
        java: ["19-ea"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        continue-on-error: true
        with:
          arguments: testCompatibility -PavroVersion=${{ matrix.avro }} -PgradleVersion=${{ matrix.gradle }}
